/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#bec6e0',
        'outline-variant': '#c3c6d7',
        'tertiary-container': '#656d84',
        'surface-variant': '#e1e3e4',
        'surface-container-highest': '#e1e3e4',
        'tertiary-fixed': '#dae2fd',
        'on-tertiary-fixed': '#131b2e',
        'inverse-on-surface': '#f0f1f2',
        'surface-container-high': '#e7e8e9',
        'primary-fixed-dim': '#b4c5ff',
        'error-container': '#ffdad6',
        'inverse-surface': '#2e3132',
        surface: '#f8f9fa',
        'primary-fixed': '#dbe1ff',
        'on-error-container': '#93000a',
        'surface-dim': '#d9dadb',
        'on-secondary-container': '#54647a',
        error: '#ba1a1a',
        'on-surface-variant': '#434655',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#d0e1fb',
        'secondary-fixed': '#d3e4fe',
        'on-primary-container': '#eeefff',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#b7c8e1',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        outline: '#737686',
        'on-tertiary-fixed-variant': '#3f465c',
        'on-secondary-fixed-variant': '#38485d',
        'on-secondary-fixed': '#0b1c30',
        'inverse-primary': '#b4c5ff',
        'surface-tint': '#0053db',
        'on-surface': '#191c1d',
        'primary-container': '#2563eb',
        background: '#f8f9fa',
        'surface-container': '#edeeef',
        secondary: '#505f76',
        primary: '#004ac6',
        tertiary: '#4d556b',
        'surface-bright': '#f8f9fa',
        'surface-container-low': '#f3f4f5',
        'on-tertiary-container': '#eef0ff',
        'on-background': '#191c1d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'stack-lg': '32px',
        'stack-xs': '4px',
        'margin-page': '32px',
        'stack-md': '16px',
        'container-max': '1440px',
        'gutter-md': '24px',
        'stack-sm': '8px',
      },
      fontFamily: {
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'headline-sm': [
          '18px',
          { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '700' },
        ],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' },
        ],
        'code-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' },
        ],
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
}
